services:
  web-dev:
    profiles: ["dev"]
    image: elmcsis-dashboard
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
      - migrate # Ensure migrations run before the web service starts

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - db_data:/var/lib/postgresql/data

  migrate:
    profiles: ["dev"]
    image: node:18 # Use a Node.js image to run Prisma commands
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DATABASE_URL: "postgresql://postgres:admin@db:5432/elmcsis-dashboard"
    depends_on:
      - db
    entrypoint: ["sh", "-c", "npm install && npx prisma migrate deploy"]

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data: